name: SliverPy
on:
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+
    branches: master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    if: startsWith( github.ref, 'refs/tags/v')
    timeout-minutes: 45

    steps:

    - id: install-secret-key
      name: GPG Secret Key(s)
      run: |
        cat <(echo -e "${{ secrets.SLIVERPY_GPG }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Python Setup
      run: python3 -m pip install --upgrade build twine hatch

    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Git Fetch Tags
      run: git fetch --prune --unshallow --tags -f

    - name: Package
      run: hatch build

    - name: Github Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ./dist/*

    - name: PyPI Upload
      env:
        TWINE_NON_INTERACTIVE: 1
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: "${{ secrets.TWINE_PASSWORD }}"
      run: python3 -m twine upload --sign --identity 9F68D30C -r pypi dist/*
